language: php

php:
  - '5.6'
  - '7.0'

notifications:
  email:
    - 303198069@qq.com

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer dump-autoload

script: vendor/bin/phpunit --verbose